### ISSUE TITLE
Error: Could not get unknown property 'artifactoryUsername' for project ':view-tools'

### ISSUE THREAD

**Issue by basejump** [9ci/grails-view-tools#16]
running gradle check on my machine.
We should add some info in the readme.md on how to build locally, run mkdocs to edit docs locally and update the ~.gradle/gradle.properties

**Comment by snimavat** [comment]
Yes, i missed docs for artifactory publishing, will update

You need to put 

```
bintrayUser=xxx
bintrayKey=xxx
artifactoryUsername=xx
artifactoryPassword=xx
```

into your ~/.gradle/gradle.properties file

**Comment by basejump** [comment]
all of those should be optional. the build should still work without having them specified.

**Comment by snimavat** [comment]
I can put a check if keys are not defined thn dont configure publishing and grails publish tasks

**Comment by snimavat** [comment]
Fixed
