### ISSUE TITLE
Configure this and use as the gold standard on how to setup our other plugins

### ISSUE THREAD

**Issue by basejump** [9ci/grails-view-tools#5]
and I’m not sure what we need to do to configure the publishing

[9:53] 
I’d like to have a pattern we follow for all the plugins in yakworks

[9:53] 
https://github.com/grails/gorm-graphql has some good ideas
and it uses https://github.com/grails/grails-common-build

and this has good examples on a base setup https://github.com/grails-guides/grails-multi-project-build/tree/master/complete

setup a grails-common-build like they did too

based on this it looks like they do ./gradlew  publish when its a snapshot

[10:15] 
https://github.com/grails/gorm-graphql/blob/master/travis-publish.sh

**Comment by snimavat** [comment]
Done
