### ISSUE TITLE
Finish refactor of AppResourceService

### ISSUE THREAD

**Issue by basejump** [9ci/grails-view-tools#6]
we want to create a test and show how to add the appResource to ViewLocator then we can add it to searchLoaders like here https://github.com/yakworks/view-tools/blob/master/test-projects/app/grails-app/conf/spring/resources.groovy

joshua [9:33 AM] 
the use case is for views.

ConfigKeyAppResourceLoader

joshua [9:25 AM] 
read this http://grailsblog.objectcomputing.com/posts/2016/08/31/retrieving-config-values.html

[9:25] 
we need to clean up and figure out how to get appResource more generic

[9:26] 
and change how it accesses config

**Comment by snimavat** [comment]
This thing should be done

**Comment by snimavat** [comment]
Done
