### ISSUE TITLE
clean up and standardize build so we can reuse it across other yaktools

### ISSUE THREAD

**Issue by snimavat** [9ci/grails-view-tools#8]

**Comment by basejump** [comment]
this will be a public repo on repo.9ci.com right>?

**Comment by snimavat** [comment]
Yes, can have a public repo.

**Comment by basejump** [comment]
based on this it looks like they do ./gradlew  publish when its a snapshot


[10:15] 
https://github.com/grails/gorm-graphql/blob/master/travis-publish.sh

**Comment by basejump** [comment]
I’d like to have a pattern we follow for all the plugins in yakworks


[9:53] 
https://github.com/grails/gorm-graphql has some good ideas

**Comment by basejump** [comment]
and it uses https://github.com/grails/grails-common-build
and this has good examples on a base setup https://github.com/grails-guides/grails-multi-project-build/tree/master/complete

**Comment by snimavat** [comment]
Yes, its easy, just configure a maven repo and gradle publish will do the job.

**Comment by basejump** [comment]
Lets use view-tools as the base. get it cleaned up and working and then we can use it as the template for how to setup the rest of the plugins

**Comment by snimavat** [comment]
Done
